// Mock product data
export const products = [
  // Hair Salons
  {
    id: 1,
    name: 'Premium Hair Treatment Package',
    category: 'Hair Salons',
    image: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=400',
    price: '$89',
    originalPrice: '$120',
    rating: 4.8,
    reviews: 234,
    duration: '90 min',
    description: 'Deep conditioning treatment with premium products',
    location: 'New York, NY',
    vendor: 'Elite Hair Studio'
  },
  {
    id: 7,
    name: 'Hair Color & Highlights',
    category: 'Hair Salons',
    image: 'https://images.unsplash.com/photo-1560869713-7d563b7c4b0c?w=400',
    price: '$180',
    originalPrice: '$220',
    rating: 4.6,
    reviews: 298,
    duration: '150 min',
    description: 'Full color service with premium highlights',
    location: 'Seattle, WA',
    vendor: 'Color Studio'
  },
  {
    id: 9,
    name: 'Haircut & Styling Package',
    category: 'Hair Salons',
    image: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=400',
    price: '$75',
    originalPrice: '$95',
    rating: 4.7,
    reviews: 412,
    duration: '60 min',
    description: 'Professional haircut with styling and blow-dry',
    location: 'San Francisco, CA',
    vendor: 'Style Studio'
  },
  {
    id: 10,
    name: 'Keratin Smoothing Treatment',
    category: 'Hair Salons',
    image: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=400',
    price: '$250',
    originalPrice: '$300',
    rating: 4.9,
    reviews: 189,
    duration: '180 min',
    description: 'Long-lasting keratin smoothing treatment',
    location: 'Miami, FL',
    vendor: 'Smooth Hair Studio'
  },
  // Nails
  {
    id: 2,
    name: 'Gel Manicure & Pedicure Combo',
    category: 'Nails',
    image: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=400',
    price: '$65',
    originalPrice: '$85',
    rating: 4.9,
    reviews: 189,
    duration: '75 min',
    description: 'Long-lasting gel polish with nail art options',
    location: 'Los Angeles, CA',
    vendor: 'Nail Artistry'
  },
  {
    id: 11,
    name: 'Acrylic Nails Full Set',
    category: 'Nails',
    image: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=400',
    price: '$55',
    originalPrice: '$70',
    rating: 4.8,
    reviews: 267,
    duration: '90 min',
    description: 'Full set acrylic nails with design',
    location: 'Chicago, IL',
    vendor: 'Nail Perfection'
  },
  {
    id: 12,
    name: 'Spa Pedicure Deluxe',
    category: 'Nails',
    image: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=400',
    price: '$45',
    originalPrice: '$60',
    rating: 4.7,
    reviews: 334,
    duration: '60 min',
    description: 'Relaxing spa pedicure with foot massage',
    location: 'Boston, MA',
    vendor: 'Luxury Nails'
  },
  // Eyebrows & Lashes
  {
    id: 3,
    name: 'Lash Extensions Full Set',
    category: 'Eyebrows & Lashes',
    image: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=400',
    price: '$150',
    originalPrice: '$180',
    rating: 4.7,
    reviews: 312,
    duration: '120 min',
    description: 'Classic, volume, or hybrid lash extensions',
    location: 'Miami, FL',
    vendor: 'Lash Luxe'
  },
  {
    id: 8,
    name: 'Brow Lamination & Tint',
    category: 'Eyebrows & Lashes',
    image: 'https://images.unsplash.com/photo-1631217868264-e5b90bb7e133?w=400',
    price: '$55',
    originalPrice: '$70',
    rating: 4.8,
    reviews: 223,
    duration: '45 min',
    description: 'Brow shaping, lamination, and tinting service',
    location: 'Portland, OR',
    vendor: 'Brow Boutique'
  },
  {
    id: 13,
    name: 'Lash Lift & Tint',
    category: 'Eyebrows & Lashes',
    image: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=400',
    price: '$75',
    originalPrice: '$95',
    rating: 4.9,
    reviews: 445,
    duration: '60 min',
    description: 'Lash lift with tint for natural curl',
    location: 'Denver, CO',
    vendor: 'Lash Studio'
  },
  // Skincare
  {
    id: 4,
    name: 'Facial Rejuvenation Treatment',
    category: 'Skincare',
    image: 'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=400',
    price: '$95',
    originalPrice: '$130',
    rating: 4.9,
    reviews: 267,
    duration: '60 min',
    description: 'Anti-aging facial with premium serums',
    location: 'Chicago, IL',
    vendor: 'Glow Spa'
  },
  {
    id: 14,
    name: 'Deep Cleansing Facial',
    category: 'Skincare',
    image: 'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=400',
    price: '$85',
    originalPrice: '$110',
    rating: 4.8,
    reviews: 389,
    duration: '75 min',
    description: 'Deep cleansing facial with extraction',
    location: 'Phoenix, AZ',
    vendor: 'Youthful Skin Spa'
  },
  {
    id: 15,
    name: 'Hydrating Facial Treatment',
    category: 'Skincare',
    image: 'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=400',
    price: '$70',
    originalPrice: '$90',
    rating: 4.7,
    reviews: 256,
    duration: '50 min',
    description: 'Intensive hydrating facial for dry skin',
    location: 'Atlanta, GA',
    vendor: 'Hydration Spa'
  },
  // Massage
  {
    id: 5,
    name: 'Deep Tissue Massage',
    category: 'Massage',
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400',
    price: '$110',
    originalPrice: '$140',
    rating: 4.8,
    reviews: 445,
    duration: '90 min',
    description: 'Therapeutic deep tissue massage for muscle relief',
    location: 'Boston, MA',
    vendor: 'Tranquil Massage'
  },
  {
    id: 16,
    name: 'Swedish Relaxation Massage',
    category: 'Massage',
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400',
    price: '$90',
    originalPrice: '$120',
    rating: 4.9,
    reviews: 523,
    duration: '60 min',
    description: 'Relaxing full body Swedish massage',
    location: 'New York, NY',
    vendor: 'Serenity Spa'
  },
  {
    id: 17,
    name: 'Hot Stone Massage',
    category: 'Massage',
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400',
    price: '$130',
    originalPrice: '$160',
    rating: 4.8,
    reviews: 312,
    duration: '90 min',
    description: 'Therapeutic hot stone massage therapy',
    location: 'Los Angeles, CA',
    vendor: 'Wellness Center'
  },
  // Makeup
  {
    id: 6,
    name: 'Bridal Makeup Package',
    category: 'Makeup',
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400',
    price: '$200',
    originalPrice: '$250',
    rating: 5.0,
    reviews: 156,
    duration: '120 min',
    description: 'Complete bridal makeup with trial session',
    location: 'Dallas, TX',
    vendor: 'Bridal Beauty Co'
  },
  {
    id: 18,
    name: 'Evening Glam Makeup',
    category: 'Makeup',
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400',
    price: '$85',
    originalPrice: '$110',
    rating: 4.9,
    reviews: 278,
    duration: '60 min',
    description: 'Professional evening glam makeup application',
    location: 'Las Vegas, NV',
    vendor: 'Glam Studio'
  },
  {
    id: 19,
    name: 'Natural Day Makeup',
    category: 'Makeup',
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400',
    price: '$65',
    originalPrice: '$85',
    rating: 4.7,
    reviews: 412,
    duration: '45 min',
    description: 'Natural everyday makeup look',
    location: 'Seattle, WA',
    vendor: 'Natural Beauty'
  },
];

