// Vendor name to ID mapping
export const vendorIdMap: { [key: string]: number } = {
  'Elite Hair Studio': 1,
  'Nail Artistry': 2,
  'Lash Luxe': 3,
  'Glow Spa': 4,
  'Tranquil Massage': 5,
  'Bridal Beauty Co': 6,
  'Color Studio': 7,
  'Brow Boutique': 8,
  'Therapeutic Touch': 9,
  'Nail Perfection': 10,
  'Highlight Studio': 11,
  'Youthful Skin Spa': 12,
};

// Mock services data
export const services = [
  {
    id: 1,
    name: 'Haircut & Styling',
    category: 'Hair Salons',
    vendor: 'Elite Hair Studio',
    vendorId: 1,
    image: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=400',
    price: '$45',
    duration: '60 min',
    rating: 4.8,
    reviews: 234,
    location: 'New York, NY',
    available: true,
    description: 'Professional haircut with styling and blow-dry'
  },
  {
    id: 2,
    name: 'Gel Manicure',
    category: 'Nails',
    vendor: 'Nail Artistry',
    vendorId: 2,
    image: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=400',
    price: '$35',
    duration: '45 min',
    rating: 4.9,
    reviews: 189,
    location: 'Los Angeles, CA',
    available: true,
    description: 'Long-lasting gel polish with nail shaping'
  },
  {
    id: 3,
    name: 'Lash Extensions',
    category: 'Eyebrows & Lashes',
    vendor: 'Lash Luxe',
    vendorId: 3,
    image: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=400',
    price: '$120',
    duration: '90 min',
    rating: 4.7,
    reviews: 312,
    location: 'Miami, FL',
    available: true,
    description: 'Classic lash extensions full set'
  },
  {
    id: 4,
    name: 'Facial Treatment',
    category: 'Skincare',
    vendor: 'Glow Spa',
    vendorId: 4,
    image: 'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=400',
    price: '$85',
    duration: '60 min',
    rating: 4.9,
    reviews: 267,
    location: 'Chicago, IL',
    available: true,
    description: 'Deep cleansing facial with extraction'
  },
  {
    id: 5,
    name: 'Swedish Massage',
    category: 'Massage',
    vendor: 'Tranquil Massage',
    vendorId: 5,
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400',
    price: '$90',
    duration: '60 min',
    rating: 4.8,
    reviews: 445,
    location: 'Boston, MA',
    available: true,
    description: 'Relaxing full body Swedish massage'
  },
  {
    id: 6,
    name: 'Bridal Makeup',
    category: 'Makeup',
    vendor: 'Bridal Beauty Co',
    vendorId: 6,
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400',
    price: '$150',
    duration: '90 min',
    rating: 5.0,
    reviews: 156,
    location: 'Dallas, TX',
    available: true,
    description: 'Complete bridal makeup application'
  },
  {
    id: 7,
    name: 'Hair Color',
    category: 'Hair Salons',
    vendor: 'Color Studio',
    vendorId: 7,
    image: 'https://images.unsplash.com/photo-1560869713-7d563b7c4b0c?w=400',
    price: '$120',
    duration: '120 min',
    rating: 4.6,
    reviews: 298,
    location: 'Seattle, WA',
    available: true,
    description: 'Full hair color service with highlights'
  },
  {
    id: 8,
    name: 'Brow Lamination',
    category: 'Eyebrows & Lashes',
    vendor: 'Brow Boutique',
    vendorId: 8,
    image: 'https://images.unsplash.com/photo-1631217868264-e5b90bb7e133?w=400',
    price: '$55',
    duration: '45 min',
    rating: 4.8,
    reviews: 223,
    location: 'Portland, OR',
    available: true,
    description: 'Brow lamination and tinting service'
  },
  {
    id: 9,
    name: 'Deep Tissue Massage',
    category: 'Massage',
    vendor: 'Therapeutic Touch',
    vendorId: 9,
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400',
    price: '$110',
    duration: '90 min',
    rating: 4.7,
    reviews: 189,
    location: 'Denver, CO',
    available: true,
    description: 'Therapeutic deep tissue massage'
  },
  {
    id: 10,
    name: 'Acrylic Nails',
    category: 'Nails',
    vendor: 'Nail Perfection',
    vendorId: 10,
    image: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=400',
    price: '$50',
    duration: '75 min',
    rating: 4.5,
    reviews: 167,
    location: 'Atlanta, GA',
    available: true,
    description: 'Full set acrylic nails with design'
  },
  {
    id: 11,
    name: 'Hair Highlights',
    category: 'Hair Salons',
    vendor: 'Highlight Studio',
    vendorId: 11,
    image: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=400',
    price: '$95',
    duration: '90 min',
    rating: 4.8,
    reviews: 201,
    location: 'San Francisco, CA',
    available: true,
    description: 'Professional hair highlighting service'
  },
  {
    id: 12,
    name: 'Facial Rejuvenation',
    category: 'Skincare',
    vendor: 'Youthful Skin Spa',
    vendorId: 12,
    image: 'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=400',
    price: '$125',
    duration: '75 min',
    rating: 4.9,
    reviews: 312,
    location: 'Phoenix, AZ',
    available: true,
    description: 'Anti-aging facial treatment'
  },
];

